mod 'puppetlabs-stdlib', '9.2.0'
mod 'puppetlabs-puppetserver_gem', '1.1.1'
mod 'puppetlabs-mysql', '15.0.0'
mod 'landcareresearch-amazon_s3', '6.0.0'
mod 'puppet-hiera', '5.0.1'
mod 'puppetlabs-inifile', '6.1.0'